---
title: Об этом сайте
type: docs
weight: 250
---

:source-highlighter: rouge
:icons: font
:sectanchors:
:toc:
:imagesdir: /docs/images

Этот сайт является документацией к link:++{{<ref "/">}}++[Эргономичному подходу].
На данный момент сайт находится в активной разработке - обращайте внимание на версии статей.

== Схема версионирования статей

Все статьи об идеях Эргономичного подхода имеют трёхзначную версию в формате x.y.z.
Смысл частей версии следующий:

. версия модели, методики или шаблона.
  Нечётные версии являются стабильными — проверенные как минимум в течении шести месяцев в коммерческом проекте.
  Чётные версии являются гипотезами — соответствующую идею я либо проверяю в текущем коммерческом проекте, либо планирую проверить в следующем;
. версия статьи.
  Особый смысл имеет только версия 0 — в этой версии статья является заглушкой, содержащей либо ссылки на посты и выступления, либо несколько предложений с основными тезисами, описывающими идею;
. минорная версия статьи.

== Тёмная тема

Этот сайт автоматически переключается на тёмную тему, если соответствующая тема выбрана в настройках ОС или браузера.
Однако подсветка синтаксиса пока что не имеет адаптации к тёмной теме.